Remove bytes from default cookie name configuration
jazzband/django-cookie-consent pull request #55
Opened 2022-03-07 03:22 UTC by some1ataplace

Goes along with PR #24

2022-03-09 21:30 UTC, sergei-maertens approved these changes

2022-03-10 23:01 UTC, sergei-maertens requested changes
I would actually like to see a test that fails without this fix and passes with the fix, as I'm not sure where exactly this fails and/or causes problems - we've been using this succesfully in our projects.

A `str` seems to be the correct approach, but PRs need to be accompanied by (regression) tests.

2022-03-11 02:00 UTC, some1ataplace commented
Agreed. I never actually had this problem myself with it being set to bytes. Would need someone to tell us how to expose the problem so we could recreate it. I simply made this PR based on the conversation from the underlying issue.

2022-09-04 21:17 UTC, sergei-maertens commented
I was able to reproduce this by removing the explicit settings from the testapp used in CI, that's enough for a regression test. This will be resolved in a couple of minutes.

2022-09-04 21:20 UTC, closed without merging