Docs-cookiebar
jazzband/django-cookie-consent pull request #90
Opened 2023-03-26 16:09 UTC by MrCordeiro

- Adds documentation for cookiebar.js. Closes #66
- Fixes cookiebar.js's `beforeDeclined` callback

2023-04-23 13:10 UTC, sergei-maertens requested changes
Really just some nitpicking in the wording/markup, other than that this seems good to merge and at least have this bit of functionality documented.

2023-04-23 13:10 UTC, sergei-maertens commented on docs/usage.rst
> +``cookiebar.js``. You can see an example of its usage in the testapp.
```suggestion
``django-cookie-consent`` can show website visitors a cookie consent message. This
message informs users that the website uses cookies and requests their consent
to store them. The script responsible for displaying the message is
``cookiebar.js``. You can see an example of its usage in the testapp.
```

2023-04-23 13:10 UTC, sergei-maertens commented on docs/usage.rst
> +  <script type="text/javascript" src={% static "cookie_consent/cookiebar.js" %}></script>
```suggestion
.. code-block:: html

  <script type="text/javascript" src="{% static 'cookie_consent/cookiebar.js' %}"></script>
```
I think this needs a blank line to properly display, and I'd also recommend properly quoting in the markup

2023-04-23 13:10 UTC, sergei-maertens commented on docs/usage.rst
> +2. In your JavaScript code, call the showCookieBar function with the
```suggestion
2. In your JavaScript code, call the ``showCookieBar`` function with the
```

2023-04-23 13:10 UTC, sergei-maertens commented on docs/usage.rst
> +  showCookieBar({
```suggestion
  window.showCookieBar({
```

IMO that makes it a bit more obvious that it's registered as a global

In the future, we should make these scripts properly scoped & make it possible to include it in potential bundlers like webpack/rollup etc. via a proper import system.

2023-04-23 13:10 UTC, sergei-maertens commented on docs/usage.rst
> +    ``null``.
please use double backticks for code to get proper code-formatting

2023-04-24 16:10 UTC, MrCordeiro commented on docs/usage.rst
> +    ``null``.
```suggestion
* ``content`` (required): A string containing the HTML for your cookie consent
    message.
* ``cookie_groups`` (optional): An array of strings representing the cookie
    consent groups. The script will only execute the scripts associated with
    these groups when the user accepts cookies.
* ``cookie_decline`` (optional): A string representing the cookie value to be set
    when the user declines cookies.
* ``beforeDeclined`` (optional): A callback function that runs before the user
    declines cookies. If you don't want to run any callbacks, set this to
    ``null``.
```

2023-04-24 16:13 UTC, MrCordeiro commented
@sergei-maertens , I've applied you suggestions

2023-04-24 16:22 UTC, sergei-maertens approved these changes

2023-04-24 16:22 UTC, merged